spring:
  application:
    name: EUREKA-SERVER
server:
  port: 8761

eureka:
  instance: hostname
  client:
    register-with-eureka: false
    fetch-registry: false
    eureka:
      client:
        serviceUrl:
          defaultZone: http://${eureka:instance:hostname}:${server:port}/eureka/