server:
  port: 8013

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/data
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    boot:
      client:
        url: http://localhost:1001
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  management:
    endpoints:
      web:
        exposure:
          includes: '*'
