server:
  port: 8011
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/data
    username: root
    password: root
    driver-class-name : com.mysql.cj.jdbc.Driver
    boot:
      client:
        url: http://localhost:1001
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka

  management:
    endpoints:
      web:
        exposure:
          includes: '*'

jwt:
  secretKey: "1HiThisIs@SrikanthPoodariHere2WeAreCreating1JwtKeyfor#theUsers.3UserAuthentication"